### PR TITLE
Relaxes dependency versioning 

### PR DESCRIPTION
**Pull request by jakubpawlowicz**
Currently both `promise` and `request` versions are pinned which makes it impossible to get patched updates within the same major version, see the commit message to a50469d.

It may require a version bump to 1.7, not sure what your policy is.

All tests are green locally.

### CODE REVIEW

**Comment by kattrali** [comment]
Thank you for the contribution, @jakubpawlowicz. The change makes sense, but would it be possible to lock to at least a minor a version which satisfies the requirements for the vulnerability patch? After taking a look at `promise`, I'm not sure either that it uses semver, and would like to mitigate the chance of dependency breakage as much as possible.

Any thoughts, @snmaynard @eanakashima?

**Comment by jakubpawlowicz** [comment]
@kattrali sure, that would work as well, only requiring similar PR in case of any future issues. Although I'm a big fan of semver it's up to owners of this package to decide.

Please let me know how you'd like to bump the versions.

**Comment by kattrali** [comment]
I poked around with this a bit, and I think it is fine for now. I may revisit and revise later. Thanks, @jakubpawlowicz.

**Comment by jakubpawlowicz** [comment]
Thank you, @kattrali!

**Pull request merged**
