### PR TITLE
Reset metaData in express middleware requestHandler

### PR DESCRIPTION
**Pull request by mathieug**
#52

### CODE REVIEW

**Comment by ConradIrwin** [comment]
Thanks for this, I think the correct fix (As you said in the issue) is to use the separate request-local metaData, see https://github.com/bugsnag/bugsnag-node/commit/2f254feb62fc97b019ca23667635f250c0c73ea8

**Comment by mathieug** [comment]
So, is `requestData` automatically reset at the end of the middlewares stack?

**Comment by ConradIrwin** [comment]
Yes, when the request finishes the domain is thrown away.

**Comment by mathieug** [comment]
Awesome. Thank you!

**Pull request closed without merging**
