### PR TITLE
Utils: Improve and correct filter/clone

### PR DESCRIPTION
**Pull request by loriopatrick**
This commit addresses performance issues in Utils.filterObject. When
filtering objects of moderate size the old logic would hang the program
for multiple seconds. Also adds support for filtering objects in arrays
and handling more complex references.

### CODE REVIEW

**Comment by kattrali** [comment]
Thanks for the contribution, @loriopatrick! 🎉  Looks good so far, though I'll need a bit of time to get through it thoroughly.

**Comment by loriopatrick** [comment]
@kattrali any progress on this?

**Comment by kattrali** [comment]
@loriopatrick got a little bogged down with other stuff, I'll have an update shortly.

**Comment by loriopatrick** [comment]
Thanks

**Pull request merged**
