### PR TITLE
Add support for sending code [Fixes #65]

### LINKED ISSUE #65: Add code support to node
We should add support for code in stacktrace

### PR DESCRIPTION
**Pull request by jacobmarshall**
screen shot 2015-11-05 at 2 13 52 pm

### CODE REVIEW

**Comment by jacobmarshall** [comment]
So right now one test is failing because I have added a `directory` property ([here](https://github.com/jacobmarshall/bugsnag-node/blob/issue/code-support/lib/error.js#L39)) to each stacktrace frame - in order to later load the original file's content. Is anybody against doing this?

I'm in the process of adding this feature to the README, and I'll also push a fix for the failing test.

**Comment by jacobmarshall** [comment]
Been using this in a recent project - tests fine. The Bugsnag stacktrace code view needs JavaScript syntax highlighting for Node.js projects though.

**Comment by kattrali** [comment]
I just got around to reviewing this, works perfectly, @jacobmarshall! Thanks!

**Comment by jacobmarshall** [comment]
Thanks @kattrali, much appreciated.

**Pull request merged**
